### ISSUE TITLE
About grouding output

### ISSUE THREAD

**Issue by nguyenquivinhquang** [FoundationVision/Groma#12]
Thanks for your wonderful work,
I want to ask which part of the code corresponds to the grounding output in section 3.2 of the paper.
![image](https://github.com/FoundationVision/Groma/assets/60070577/a0793bda-0fc5-45b8-9e44-36d86461b8bd)

**Comment by machuofan** [comment]
Thanks for your interest in our work. The codes of preparing grounded output can be founded in dataset definitions, e.g., [flicker.py](https://github.com/FoundationVision/Groma/blob/101f04f5a2c75c3adbaaec73f0b0723e4e3937b0/groma/data/datasets/flickr.py#L207-L217).
