### ISSUE TITLE
Finetuning and dataset formatting guidelines

### ISSUE THREAD

**Issue by hinsonan** [FoundationVision/Groma#2]
Very cool work and congrats on what you have accomplished. Wanted to know if you all had plans to release a finetuning guide and how to format datasets

**Comment by hinsonan** [comment]
thank you for your response. Perhaps if i have some time i can update documentation and provide a fine-tuning section. Someone else may be able to get to it sooner than me

**Comment by Wuwenji18** [comment]
> 感谢您的回复。也许如果我有时间，我可以更新文档并提供一个微调部分。其他人可能比我更早到达

Hello! Have you fineturn the model on your dataset? Best wish!
