### ISSUE TITLE
如何使用该模型进行区域描述提问

### ISSUE THREAD

**Issue by coko12** [FoundationVision/Groma#20]
区域理解时如何进行提问。假设我想让算法描述box_xyxy[50,50,200,270]的物体如何写提问的问题。
是这样提问吗：Please briefly describe this region [50,50,200,270]?

**Comment by machuofan** [comment]
Not exactly, you need to pass the box coordinates to `model.generate()`. We provide an example in `run_groma.py` [link](https://github.com/FoundationVision/Groma/blob/d3a95b6c2657dcb5c05f326da8895f521cf60009/groma/eval/run_groma.py#L93).

For user prompt, you can follow this format:
```
Please briefly describe <roi><refer_box></roi> <refer_feat>.
```

**Comment by LLH-Harward** [comment]
Hello, great work! Could you provide more details? If I want to input the object's label and bounding box to Groma to assist in generating more accurate image descriptions, how should I write the prompt?

**Comment by LLH-Harward** [comment]
@machuofan
