### ISSUE TITLE
Bounding box format

### ISSUE THREAD

**Issue by liukc19** [FoundationVision/Groma#21]
Thank you for your great work.
I found that groma performs poorly on some object detection tasks, which makes it difficult for me to determine whether the problem occurs in the inference phase or the detection phase when using groma to do some complex VQA tasks.
Do you plan to fix the bug of misaligned bounding box format when extracting region feature?

**Comment by machuofan** [comment]
Hi there, you can check if the target boxes are missed by the region proposer by commenting out the [following lines](https://github.com/FoundationVision/Groma/blob/d3a95b6c2657dcb5c05f326da8895f521cf60009/groma/eval/run_groma.py#L112-L114), which draws every single box detected by ddetr after nms and thresholding.

I have tried re-training the model after changing the box format from [cx, cy, w, h] to [x1, y1, x2, y2] for roi_align input, as reported in #11. But the performances decreased on all benchmarks. Still working on how could this happen...

**Comment by Ethan-yh** [comment]
Hi, did you find out why the performance of the model decreased after aligning the bounding boxes? That is really weird. @machuofan
