### ISSUE TITLE
Can groma be fine-tuned on a custom dataset?

### ISSUE THREAD

**Issue by Ethan-yh** [FoundationVision/Groma#22]
My new dataset has bounding box coordinates like [x1, y1, x2, y2]. How can I match the bounding box of the new dataset with the region generated by the region proposer?

**Comment by 77h2l** [comment]
same, keep an eye on this. it seems the repo is not going to update, right?

**Comment by machuofan** [comment]
No worries. You can do box format conversion online when loading custom data, just like [this](https://github.com/FoundationVision/Groma/blob/d3a95b6c2657dcb5c05f326da8895f521cf60009/groma/data/datasets/refcoco_rec.py#L159).

For more details on finetuning on custom data, please refer to #2.

**Comment by Ethan-yh** [comment]
Thank you for your reply, now I understand your model approach.
