### ISSUE TITLE
Can region proposer discover all regions of interest?

### ISSUE THREAD

**Issue by JewelShiny** [FoundationVision/Groma#26]
I have found that all user input and output boxes are converted to the boxes output by the region proposer by finding the maximum IoU. What if the output or input box is not in the region proposer output? Can the region proposer guarantee all possible regions?

**Comment by machuofan** [comment]
The user input boxes are directly passed to the region encoder. Groma merges regions detected by region proposer and user input together, before NMS. To ensure user input boxes are not filtered out, we assign confidence score 1 to these boxes during NMS.

The region proposer is designed to discover the most of the potential target regions,. But still, it is possible that some small objects or object parts are missed by the proposer.
