### ISSUE TITLE
unable to load local weight

### ISSUE THREAD

**Issue by liukc19** [FoundationVision/Groma#3]
I have manually downloaded the model weights from Hugging Face and tried fine-tuning the model using the following command.
`bash scripts/vl_finetune.sh ./groma-7b-pretrain ./train_history/`
But the program still tries to access the weights from the website.
I set the following output for debug.
![image](https://github.com/FoundationVision/Groma/assets/76678452/5701d419-66fd-46ba-b49a-dc9dab23bcfe)
![image](https://github.com/FoundationVision/Groma/assets/76678452/2ee00c6b-88c7-4fbc-9993-2a371fd40b51)
And this is the output:
![image](https://github.com/FoundationVision/Groma/assets/76678452/10f7722a-6fee-4933-8341-d894b7598b2f)
It seems that the program is unable to local model weight?

Looking forward to your reply.

**Comment by liukc19** [comment]
Sorry, the issue seems to be occurring here.
![image](https://github.com/FoundationVision/Groma/assets/76678452/b89daaaf-6ecd-411a-8aeb-753b63a1c8c9)
![image](https://github.com/FoundationVision/Groma/assets/76678452/51e92bb6-ff4a-4034-9087-4d91cc119604)
So what is the `vis_encoder_path`？

**Comment by machuofan** [comment]
Thanks for the feedback. The bug occurs as the program is looking for a local DINOv2-L checkpoint to initialize CustomDDETRModel. This is not an expected behavior. A quick fix is to delete `vis_encoder_path: checkpoints/dinov2-large` in `groma-7b-pretrain/config.json`. I will fix the initialization logic soon later.

**Comment by liukc19** [comment]
"Thank you for your prompt feedback. I have encountered a new issue. Do you know why this is happening?"
![image](https://github.com/FoundationVision/Groma/assets/76678452/c4f6b27b-5d3d-4ba1-a6cf-051c11af4601)

**Comment by liukc19** [comment]
I think this error comes from a failed installation of mmcv. Could you clarify the relationship between the mmcv folder in your repository and the mmcv package?

**Comment by machuofan** [comment]
We inherited the mmcv folder from GPT4ROI. I think it is originated from mmcv==1.4.7.
