### ISSUE TITLE
Batch Size in Alignment Pretraining

### ISSUE THREAD

**Issue by alichr** [FoundationVision/Groma#39]
Based on the scripts you provided, the batch size per GPU is set to 2, which totals 16 across 8 GPUs, and this configuration is working fine. However, in the paper, the total batch size is mentioned as 128, with 16 per GPU. When I attempt to train the model with this batch size, I encounter a "out of memory" error.

![Screenshot from 2024-12-16 11-47-08](https://github.com/user-attachments/assets/b2a3d184-d37c-4d00-852c-2f36ba809d1f)

**Comment by machuofan** [comment]
Thanks for your attention. Since we use `gradient_accumulation_steps=8`, the effective batch size of the script is actually 16*8 = 128.

**Comment by alichr** [comment]
Thank you for getting back to me so quickly. I appreciate your work; the provided code is clean and easy to follow.
