### ISSUE TITLE
有没有小一点的模型？ 24G现存可用的

### ISSUE THREAD

**Issue by traddo** [FoundationVision/Groma#8]
FoundationVision/groma-7b-finetune 太大了。

**Comment by machuofan** [comment]
Groma-7b is the smallest model we have. It takes 30-40G memory for inference on a single GPU. You may consider using int8 quantization to make it run with 24G memory.

**Comment by AllenDun** [comment]
is there a guide to use int8 quantization for Groma

**Comment by machuofan** [comment]
I find this [huggingface guide](https://huggingface.co/docs/transformers/main_classes/quantization) could be helpful. You can first try with fp16, then int8. The implementation of [load_pretrained_model()](https://github.com/haotian-liu/LLaVA/blob/c121f0432da27facab705978f83c4ada465e46fd/llava/model/builder.py#L26) in LLaVA also serves as a good example.

**Comment by vcadillog** [comment]
I had quantized the model to 4 bit, it needs at least 7G GPU, you can download it from huggingface and see how to work with it in my fork here.
https://github.com/vcadillog/Groma-4bits/

**Comment by machuofan** [comment]
@vcadillog Thanks for sharing. The inference now supports `fp16`, `int8`, and `int4` quantization.

**Comment by XuYunqiu** [comment]
Hi @machuofan, 
can we split the model weights on multiple GPUs with FP16?

**Comment by machuofan** [comment]
Hi there, do you mean using FSDP in inference [link](https://github.com/meta-llama/llama-recipes/issues/213)?

**Comment by XuYunqiu** [comment]
Thanks for your prompt response.
I am not familiar with FSDP. I mean the similar operation like `load_checkpoint_and_dispatch ` used in this [link](https://huggingface.co/THUDM/cogvlm-chat-hf).

**Comment by machuofan** [comment]
Thanks for pointing out this interesting feature. I haven't tested it before. But considering the model and the function `load_checkpoint_and_dispatch` are both native to huggingface, I think it could probably work, and worth having a try.
